package com.qianfeng.day10_alipay.db;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.qianfeng.day10_alipay.bean.Product;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "tb_shopping_card".
*/
public class ProductDao extends AbstractDao<Product, Long> {

    public static final String TABLENAME = "tb_shopping_card";

    /**
     * Properties of entity Product.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property _id = new Property(0, Long.class, "_id", true, "_id");
        public final static Property ProductName = new Property(1, String.class, "productName", false, "PRODUCT_NAME");
        public final static Property ProductPrice = new Property(2, float.class, "productPrice", false, "PRODUCT_PRICE");
        public final static Property ProductNum = new Property(3, int.class, "productNum", false, "PRODUCT_NUM");
        public final static Property ProductId = new Property(4, Long.class, "productId", false, "PRODUCT_ID");
    }


    public ProductDao(DaoConfig config) {
        super(config);
    }
    
    public ProductDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"tb_shopping_card\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: _id
                "\"PRODUCT_NAME\" TEXT," + // 1: productName
                "\"PRODUCT_PRICE\" REAL NOT NULL ," + // 2: productPrice
                "\"PRODUCT_NUM\" INTEGER NOT NULL ," + // 3: productNum
                "\"PRODUCT_ID\" INTEGER);"); // 4: productId
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"tb_shopping_card\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, Product entity) {
        stmt.clearBindings();
 
        Long _id = entity.get_id();
        if (_id != null) {
            stmt.bindLong(1, _id);
        }
 
        String productName = entity.getProductName();
        if (productName != null) {
            stmt.bindString(2, productName);
        }
        stmt.bindDouble(3, entity.getProductPrice());
        stmt.bindLong(4, entity.getProductNum());
 
        Long productId = entity.getProductId();
        if (productId != null) {
            stmt.bindLong(5, productId);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, Product entity) {
        stmt.clearBindings();
 
        Long _id = entity.get_id();
        if (_id != null) {
            stmt.bindLong(1, _id);
        }
 
        String productName = entity.getProductName();
        if (productName != null) {
            stmt.bindString(2, productName);
        }
        stmt.bindDouble(3, entity.getProductPrice());
        stmt.bindLong(4, entity.getProductNum());
 
        Long productId = entity.getProductId();
        if (productId != null) {
            stmt.bindLong(5, productId);
        }
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public Product readEntity(Cursor cursor, int offset) {
        Product entity = new Product( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // _id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // productName
            cursor.getFloat(offset + 2), // productPrice
            cursor.getInt(offset + 3), // productNum
            cursor.isNull(offset + 4) ? null : cursor.getLong(offset + 4) // productId
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, Product entity, int offset) {
        entity.set_id(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setProductName(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setProductPrice(cursor.getFloat(offset + 2));
        entity.setProductNum(cursor.getInt(offset + 3));
        entity.setProductId(cursor.isNull(offset + 4) ? null : cursor.getLong(offset + 4));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(Product entity, long rowId) {
        entity.set_id(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(Product entity) {
        if(entity != null) {
            return entity.get_id();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(Product entity) {
        return entity.get_id() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
